### ISSUE TITLE
请说明环境基本运行情况

### ISSUE THREAD

**Issue by txgo** [leancloud/leanengine-node-sdk#10]
比如：入口文件、启动顺序、安装了哪些到哪个目录？这些隐含的步骤

**Comment by sdjcw** [comment]
你好，我没明白你需要的是什么。
该 SDK 其实就是一个标准的 Node.js 组件，使用 Npm 管理，这种包管理的文档可以见这里：https://docs.npmjs.com/

https://github.com/leancloud/leanengine-node-sdk/blob/master/package.json
描述了该包的基本信息，包括名称，版本，依赖等等。你可以从这个文件开始了解。
