### ISSUE TITLE
支持async await 吗？

### ISSUE THREAD

**Issue by chenshuhong** [leancloud/leanengine-node-sdk#101]
用leancloud存储功能查询后能不能不返回promise，我想用async await 来处理

**Comment by leeyeh** [comment]
返回的是 Promise，see https://leancloud.github.io/javascript-sdk/docs/AV.Query.html#find

**Comment by chenshuhong** [comment]
我知道返回promise，没有find的同步方法吗？想用async await

**Comment by leeyeh** [comment]
你需要 await 一个 Promise。建议阅读： https://developers.google.com/web/fundamentals/getting-started/primers/async-functions

**Comment by chenshuhong** [comment]
搞定了，谢谢，刚刚学nodejs
