### ISSUE TITLE
我们的 Bug 给用户清晰的「请升级 SDK」提示

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/leanengine-node-sdk#108]
https://forum.leancloud.cn/t/hook/14512

这个问题， @jysperm 说是：2.0 和命令行工具配合的一个 Bug，升级到最新版可解。

既然界定为我们的锅的 bug，能否**主动在云引擎日志**里告知用户升级 SDK。 @aisk @sdjcw 大佬们来出出主意。

**Comment by jysperm** [comment]
https://github.com/leancloud/cloud-code/issues/1287
