### ISSUE TITLE
web 实例图表里有不合适的数据

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/leanengine-node-sdk#109]
https://leanticket.cn/t/leancloud/4774

499 表示客户端主动断开了连接，请求可能还未被发送到某个具体的实例，所以是 unknown。

那这种 pending 中的请求，不应该被展示在控制台图表里，会让用户产生误解。

**Comment by sdjcw** [comment]
我觉得可以留着，但是在文档上说明这种情况的原因。毕竟这也可能说明存在一些状况。

**Comment by jysperm** [comment]
我觉得还是应该留着，可以在图表页加一些说明
