### ISSUE TITLE
增加本地调试 Cloud 函数的功能

### ISSUE THREAD

**Issue by sdjcw** [leancloud/leanengine-node-sdk#11]
类似命令行工具之前的 localhost:3000/avos 页面。

**Comment by aisk** [comment]
我觉得可以直接在命令行工具里面提供，这样不用 Python 和 Node 都写一份了。

**Comment by sdjcw** [comment]
那可能要命令行工具单独启动一个 webServer 了，然后这个 webServer 发请求到 LeanEngine 的本地 server。

**Comment by sdjcw** [comment]
已经完成 https://github.com/leancloud/avoscloud-code-command/commit/2ec2adf798eaa66565552c236543f09ca8125fc4
