### ISSUE TITLE
sdk调用云函数本地报错getSessionToken is not a function

### ISSUE THREAD

**Issue by wahack** [leancloud/leanengine-node-sdk#113]
本地调用云函数

`AV.Cloud.run('name', data, {user: currentUser, remote: true})`

报错：
`...options.getSessionToken is not a function`

跟踪后发现是这端代码的问题
[https://github.com/leancloud/leanengine-node-sdk/blob/master/lib/cloud.js#L38](https://github.com/leancloud/leanengine-node-sdk/blob/master/lib/cloud.js#L38)

```
if (options.remote) {

    if (options.user) {

      options.sessionToken = options.sessionToken || options.getSessionToken();

    }
    return originalCloudRun.apply(null, arguments);
}

```

将`options.getSessionToken();`改为`options.user.getSessionToken();`便正常了

另外文档里没有关于`remote:true`这个参数的说明啊，看不出来其是放在第三个参数`AuthOptions`里[https://leancloud.github.io/javascript-sdk/docs/AV.Cloud.html#.run](https://leancloud.github.io/javascript-sdk/docs/AV.Cloud.html#.run)

**Comment by jysperm** [comment]
`...options.getSessionToken is not a function` 确实如此，我们会尽快修复这个问题。

AV.Cloud.run 这个函数在 JS SDK 和 Node SDK 下的行为是不一样的，只有在 Node SDK 才有 remote 这个参数，文档在 https://github.com/leancloud/leanengine-node-sdk/blob/master/API.md#avcloudrun

**Comment by jysperm** [comment]
2.0.4 修复了这个问题
