### ISSUE TITLE
AV.User.current() 不返回 null

### ISSUE THREAD

**Issue by lxmfly123** [leancloud/leanengine-node-sdk#116]
根据[升级到云引擎 Node.js SDK 1.0](https://leancloud.cn/docs/leanengine-node-sdk-upgrade-1.html)这篇文章，在云引擎中使用 `AV.User.current() ` 应返回 `NULL`，然而目前在 **3.0.0** 版本中仍然返回了实际的 AVUser 实例。

**Comment by leeyeh** [comment]
fixed in leancloud-storage@3.0.4
