### ISSUE TITLE
云引擎中设置 serverUrl 不起作用

### ISSUE THREAD

**Issue by jwfing** [leancloud/leanengine-node-sdk#137]
代码如下：
```
const AV = require('leanengine');
AV.init({appId: process.env.LC_APP_ID,
appKey: process.env.LC_APP_KEY,
masterKey: process.env.LC_APP_MASTER_KEY,
serverURLs: "http://localhost:8080"});
```
最终还是请求到了公有云。

**Comment by leeyeh** [comment]
我没能复现这个问题： 

https://github.com/leancloud/node-js-getting-started/tree/issue-137

lean up 启动之后打印的 config 能看到正确覆盖的 urls。
带着 sessionToken call hello function 也能看到正确的请求了 localhost。

能否提供一个可以复现的代码？

**Comment by jysperm** [comment]
没有后续了，没有发现类似问题，关掉了
