### ISSUE TITLE
使用 node 0.12 + 后，V8 自带的 Promise 处理异步时会丢失 process.domain，导致用户登录信息丢失

### ISSUE THREAD

**Issue by filod** [leancloud/leanengine-node-sdk#14]
如题，建议更改目前用户登录的设计。

process.domain在未来会被废弃，其他会导致 process.domain 丢失的情况暂不明确

**Comment by sdjcw** [comment]
谢谢反馈，我们讨论下。

@wangxiao @killme2008 @aisk

**Comment by sdjcw** [comment]
将来的版本会彻底移除 domain 模块的使用。
