### ISSUE TITLE
[bug] 在云函数中使用 include 后查询的结果会丢失

### ISSUE THREAD

**Issue by filod** [leancloud/leanengine-node-sdk#15]
例如

```
query = new AV.Query(Post)
query.include('comment').find().then(function(post){
  res.sucess(post)
})
```

前端接受到的 post 的 comment 字段会丢失

**Comment by hjiang** [comment]
@aisk @sdjcw

**Comment by sdjcw** [comment]
你好，因为云代码方法返回的只是普通的 JSON 字符串，而不是 AVObject 结构，所以 include 的字段默认情况下不会返回给客户端。
如果要这么做，有个变通的办法就是类似于这样做：

```
res.success({post: post, comment: post.get('comment')})
```

后续我们会开放另外一个接口，直接可以传入或者返回 AVObject 对象，这样使用会方便一些。

**Comment by filod** [comment]
我现在是自己 hack 了序列化/反序列化 AVObject 的功能临时撑着，希望早日出官方 api。

**Comment by sdjcw** [comment]
v0.2.0 已经发布，支持 RPC 调用，直接返回 AVObject 对象：https://github.com/leancloud/leanengine-node-sdk/blob/master/CHANGELOG.md

等待各个 SDK 更新后即可使用。
