### ISSUE TITLE
Variable 'masterKey' implicitly declared.

### ISSUE THREAD

**Issue by leeyeh** [leancloud/leanengine-node-sdk#18]
#### Occurred on:
- **Commit**:  8166b139d526d138e63e38d1ffbde895963a68f6
- **File**:    [lib/leanengine-sdk.js](https://github.com/leancloud/leanengine-node-sdk/blob/8166b139d526d138e63e38d1ffbde895963a68f6/lib/leanengine-sdk.js)
- **LineNum**: [86](https://github.com/leancloud/leanengine-node-sdk/blob/8166b139d526d138e63e38d1ffbde895963a68f6/lib/leanengine-sdk.js#L86)
- **Code**:    `masterKey = req.body._MasterKey;`
#### Currently on:
- **Commit**:  26a7432e0a03bfcfec12b7b014aef64c96ee0431
- **File**:    [lib/leanengine.js](https://github.com/leancloud/leanengine-node-sdk/blob/26a7432e0a03bfcfec12b7b014aef64c96ee0431/lib/leanengine.js)
- **LineNum**: [94](https://github.com/leancloud/leanengine-node-sdk/blob/26a7432e0a03bfcfec12b7b014aef64c96ee0431/lib/leanengine.js#L94)

**Comment by sdjcw** [comment]
fixed 41adf5d17695b79ce0e31e5802e7bfd9963e9b1a
