### ISSUE TITLE
Hook 回调不支持 File 类型

### ISSUE THREAD

**Issue by leeyeh** [leancloud/leanengine-node-sdk#23]
https://github.com/leancloud/leanengine-node-sdk/blob/4bfec5149b322003cff550294ff9937a0feb9476/lib/leanengine.js#L270

hook 回调中的 `request.object` 没有正确处理 `_File` 类型。所以 `url()` 等 api 不可用。

https://forum.leancloud.cn/t/topic/2973

**Comment by sdjcw** [comment]
@jysperm cool~!
