### ISSUE TITLE
支持 beforeUpdate

### ISSUE THREAD

**Issue by killme2008** [leancloud/leanengine-node-sdk#25]
类似 beforeSave，约定保持一致，只是名字换了

@sdjcw 

今天凌晨上线。

beforeSave 的  `request.object` 是将更新作用到当前对象后的临时新对象，它不保证是对象更新后的状态，而只是“当时”的最新状态。

**Comment by sdjcw** [comment]
无法判断是哪个字段更新了吧？

**Comment by killme2008** [comment]
是的

**Comment by sdjcw** [comment]
备注下：request.object 不能修改属性，但是可以通过 error 响应来阻止修改。

**Comment by killme2008** [comment]
增加了字段  `_updatedKeys` ，表示更改的字段数组。

@sdjcw @aisk 尽快实现和补充文档吧。
