### ISSUE TITLE
「未捕获异常处理器」更改实现

### ISSUE THREAD

**Issue by sdjcw** [leancloud/leanengine-node-sdk#29]
Node.js 4.0 已经不推荐使用 domain 模块，所以我们未处理异常的处理方式要修改了。可能还是要使用 https://nodejs.org/api/process.html#process_event_uncaughtexception ，顺便看下 https://nodejs.org/api/process.html#process_event_unhandledrejection ，关于 promise 未处理异常的处理。

**Comment by jysperm** [comment]
按我的经验，最好的错误处理就是保证每个错误都被正确地逐级传递回 express/connect 的路由，这样就可以在 express 的错误处理函数中统一处理了，也不需要 domain 或者 uncaughtException，所有异步操作都使用 Promise 会让错误传递变得简单许多，callback 风格的话则繁琐一些。

目前 domain 做了两件事情：向客户端返回 500、打印错误信息到标准输出，uncaughtException 的话恐怕不太容易实现向客户端返回 500，因为 uncaughtException 只能拿到 error 对象，而 domain 的话是可以得到 req 得。

官方文档上建议将 uncaughtException 捕捉到的异常视为严重的错误（应该用第一段的方法避免 Uncaught Exception），仅用于记录日志，随后就重启程序。这样说起来，如果用 uncaughtException 捕捉常规错误的话，恐怕并不会比用 domian 捕捉错误更好。

**Comment by sdjcw** [comment]
是的。
但是客观现实是：主体代码是用户写的，我们没有办法强制每一个用户代码都很有效的处理所有的异常。我们增加 uncaughtexception 只是为了让用户代码的疏漏不至于导致 Node.js 进程退出，因为退出带来的代价太大了，会导致用户节点临时不可用。

虽然 uncaughtException 没办法给当此请求返回 500，但是现在看起来没有更好的办法了。

可以理解为：我们要做最后一层防护网。

**Comment by jysperm** [comment]
已在示例项目中添加
