### ISSUE TITLE
本地 avoscloud 调试工具无法测试 call

### ISSUE THREAD

**Issue by lzwjava** [leancloud/leanengine-node-sdk#37]
![image](https://cloud.githubusercontent.com/assets/5022872/11334332/4fa06144-920f-11e5-9cdc-3d23f64bf847.png)

这里是发出 /functions 的请求。

@jysperm @sdjcw

**Comment by jysperm** [comment]
@sdjcw （avoscloud-code-command 中）`public/index.html` 和 `lib/index.html` 内容是重复的，似乎后者并没有被用到，是否可以删除？

**Comment by jysperm** [comment]
已包含在刚刚发布的 0.9.2 版本命令行工具
