### ISSUE TITLE
有关实现不依赖 domain 的用户状态管理的几种方案

### ISSUE THREAD

**Issue by jysperm** [leancloud/leanengine-node-sdk#38]
## 每次操作都需要传 sessionToken 参数

```
var Topic = AV.Object.extend('Topic');

AV.Cloud.define('func', function(request, response) {
  var query = new AV.Query(Topic);
  query.find({
    sessionToken: request.user._sessionToken,
    success: function(results) {
      response.success(results);
    }
  })
});
```

实现简单、容易理解；但用户需要修改现有代码，很容易遗漏某些地方，需要在函数间传递 user.
## 为每个请求提供一个 AV 实例

```
AV.Cloud.define('func', function(request, response) {
  var Topic = request.AV.Object.extend('Topic');
  var query = new AV.Query(Topic);
  query.find({
    success: function(results) {
      response.success(results);
    }
  })
});
```

可以通过改写 AV._request 来实现，用户需要修改一部分代码，也需要在函数间传递 AV.

**Comment by aisk** [comment]
后面这种 API 看上去比较好看，但是如果有在全局 extend  出来的对象，在当前函数内 new 然后再 save，要如何支持？

**Comment by sdjcw** [comment]
假如我有一个 foo.js 的模块封装 CRUD：

```
var Foo = AV.Object.extend('Foo');

exports.create = function(foo, cb){
  ...
}

exports.find = function(options, cb) {
  var q = new AV.Query(Foo);
  q.find(options, {
    success: function(datas) {
      cb(null, datas);
    }
  })
}
```

对于这类模块，每次构造 AV 的情况，需要每次都 “初始化” 这个 foo 的模块的。。。

**Comment by jysperm** [comment]
- 提供禁用用户会话的选项（例如 AVUser.disableCurrentUser(), Parse 是叫 disableUnsafeCurrentUser()），启用后 AVUser.current() 将不会返回数据，AVUser.logIn 等方法也不会向 `AVUser._currentUser` 写入数据。Node SDK 方面也不会在调用这些方法时向 domain 写入数据（可以考虑也不为请求创建 domain），亦不会在请求结束时从 domain 向客户端写回 Cookie. 
- 在 JavaScript SDK 所有会产生网络请求的方法的 options 参数里添加一个 sessionToken 参数，以替代来自 `AVUser._currentUser` 中的 sessionToken; 为了方便从 User 对象上获取 sessionToken, 还要加一个 `user.sessionToken()` 的函数（或者叫 `getSessionToken()`）返回 `user._sessionToken`.
- 在 Node SDK 的 request 和 response 对象上提供读取和设置用户信息的方法：request.currentUser(), request.sessionToken(), response.saveCurrentUser().

我来解决一下JavaScript SDK currentUser 在 Node 环境的问题，初步打算实现这么几个修改。

---

具体的使用场景（假设用户已完全接受了新的机制），首先为了兼容原有代码，默认保持之前的行为，需要用户在程序启动时自行禁用 currentUser:

```
var AV = require('leanengine');
AV.User.disableCurrentUser();
```

在禁用 currentUser 之后，`AV.User.current()` 总是返回空数据（可以考虑打印一条警告），用户必须在路由中从 request 对象上获取当前用户的信息：

```
// 云函数
AV.Cloud.define('profile', function(request, response) {
  var user = request.currentUser()
  response.success({
    name: user.get('name')
  });
});

// 普通 Express 路由
app.get('/profile', function(request, response) {
  var user = request.currentUser()
  response.json({
    name: user.get('name')
  });
});
```

禁用 currentUser 后，`AV.User.logIn` 也不会在内存中储存数据，只是会返回登录后的用户，用户需要自行保存 User 对象，例如实现一个自定义的登录接口：

```
app.get('/login', function(request, response) {
  AV.User.login(request.body.name, request.body.password).then(function(user) {
    response.saveCurrentUser(user);
    response.send();
  });
});
```

从上面的代码可以看出如果用户需要将当前用户的登录状态（sessionToken）写回 Cookie, 需要自行调用 `response.saveCurrentUser(user)`（这个函数名还需要斟酌一下，因为 saveCurrentUser 和 disableCurrentUser 放在一起很令人困惑）。

从「保持抽象层级的一致性」的角度，写回 Cookie 的操作确实应该在路由（或所谓 Controller）中完成，相信有过 Web 后端编程经验的人还是可以理解这一点的，所以我们更建议用户在完成业务操作后将 user 传回路由层进行回写，而不是将 response 传递到业务函数中。

```
app.get('/login', function(request, response) {
  loginLogic().then(function(user) {
    res.saveCurrentUser(user);
    res.send();
  });
});

function loginLogic(args) {
  var username = // Other logics
  var password = // Other logics
  return AV.User.login(username, password);
}
```

如果用户需要进行数据查改，则必须在 `AVQuery.find`、`AVObject.fetch`, `AVObject.save` 之类的函数的 options 参数中加入一个 sessionToken, 这个 sessionToken 可以从 request 对象或 user 对象上得到。出于「保持抽象层级的一致性」的考虑，我们要建议用户在函数间传递 user 对象而不是 request 对象：

```
app.get('/friends', function(request, response) {
  getFriends(request.currentUser()).then(function(friends) {
    response.json(friends);
  });
});

function getFriends(user, otherOptions) {
  user.fetch({
    include: 'friends'
  }, {
    sessionToken: user.sessionToken()
  }).then(function() {
    // Other logics
    return user.get('friends');
  });
}
```

如果用户没有传递 sessionToken, 则不向服务器发送 sessionToken, 相当于匿名访问，很有可能出现没有权限的情况，这个可能需要在文档中特别地提醒。

以上就是 `AV.User.disableCurrentUser()` 这个修改产生的影响，关于每个方法都需要传递 sessionToken 比较繁琐的这一点，之后可以考虑通过一些高层次的 API（但仍基于上述的基本 API）来进行优化，例如下面是我想到的一种方法，仅当抛砖引玉：

```
app.post('/updatePost', function(request, response) {
  var query = new AV.Query(Post);
  query.get(request.body.id).then(function(post) {
    updatePostBody(post.asUser(request.currentUser())).then(function(post) {
      response.json(post);
    });
  });
});

function updatePostBody(post) {
  post.body = //...
  return post.save(); // 因为在路由中已经调用了 post.asUser, 这里不必传 sessionToken.
}
```

在 find 的时候也可以将查询到的所有对象都绑定到用户：

```
query.find({asUser: request.currentUser()}).then(function(objects) {
  // 在 objects 中的对象上进行查改操作不需要传递 sessionToken.
});
```

**Comment by leeyeh** [comment]
> 为了兼容原有代码，默认保持之前的行为，需要用户在程序启动时自行禁用 currentUser:

如果用户是在线定义，那么他无法「自行禁用」

**Comment by aisk** [comment]
高层次 API 实现方法，我觉得很容易让用户混乱这个对象是否绑定了用户。不如还是所有用到的地方显式传递 user 对象比较方便。

**Comment by wangxiao** [comment]
```
app.get('/friends', function(request, response) {
  getFriends(request.currentUser()).then(function(friends) {
    response.json(friends);
  });
});

function getFriends(user, otherOptions) {
  user.fetch({
    include: 'friends'
  }, {
    sessionToken: user.sessionToken()
  }).then(function() {
    // Other logics
    return user.get('friends');
  });
}
```

这里为什么要传 sessionToken ？
user 不是 request.currentUser() ，内部应该可以去到 token ，就不要让用户再传入一次了。

**Comment by jysperm** [comment]
@aisk 我只是举个例子，所谓的高层次 API 并不包含在此次修改
@wangxiao 这是个特例 .... 如果不是 user.fetch, 而是一个普通的 Class 的 fetch 呢

**Comment by wangxiao** [comment]
我的理解，既然这个 user 对象中肯定是有 token 的，就别让用户再自己取一次了。

**Comment by hjiang** [comment]
如果在服务端环境下 User.currentUser 是不安全的，应该自动禁用，不要让用户去增加那一行代码。我们可以检测出有哪些用户在调用这个方法，然后通知他们修改。

**Comment by jysperm** [comment]
@hjiang  但现在几乎所有的代码都用了它，包括我们自己的 SDK 也在用，所以这个切换还是需要一个过程的，一开始还是需要用户自行设置。

**Comment by sdjcw** [comment]
@jysperm 所以建议直接升级一个大版本号，然后重新设计这块。

**Comment by wangxiao** [comment]
恩，如果需要重新设计的地方，都写个需求，放到 2.0 需求收集里面吧。

不要太怕修改，保守的基础上也要做修正，毕竟所有服务，包括所有 SDK，未来的用户量一定远超现在的用户量，所以未来的用户得用到一个更好的 SDK，调整接口也是为了更多用户的体验。

**Comment by jysperm** [comment]
@wangxiao 这些修改并不会给 JS SDK 的前端使用带来不兼容的变化，所以和 JS SDK 2.0 关系不大，到时候升 Node SDK 的版本就好。

**Comment by wangxiao** [comment]
哦，好的，才发现是在 LeanEngine SDK 里面的。。。Orz...

**Comment by sdjcw** [comment]
但是这个修改最好写在 js-sdk 里面，让 js-sdk 适应从浏览器和 Node.js 两种环境。

**Comment by wangxiao** [comment]
这个 SDK 是干啥的？怎么定位的？

**Comment by leeyeh** [comment]
我建议直接在 js-sdk master（现在是 1.0.0-rc5） 上改吧，1.0.0 同时启用了 keep-alive。

**Comment by jysperm** [comment]
按照 JS SDK 2.0 中的讨论，需要（在 JS SDK 中）用 http 模块重写 AV._request 之后才能继续 currentUser 的修改，因为现在的 xmlhttprequest 模块和 domain 存在不明原因的不兼容（会多出一层 domain, 原因不明）。
