### ISSUE TITLE
不是所有的 request 参数都有 meta 信息

### ISSUE THREAD

**Issue by leeyeh** [leancloud/leanengine-node-sdk#39]
从代码看，目前只有「自定义函数」与所有「after」类型的 hook 的 request 参数带有 meta 信息。

**Comment by jysperm** [comment]
这一点已经在 https://github.com/leancloud/leanengine-node-sdk/pull/45 中统一了，但目前 meta 中只有客户端的 IP, 在 Hook 里获取客户端 IP 并没有意义（因为是云存储那边发过来的请求），所以在 https://github.com/leancloud/leanengine-node-sdk/pull/56 中我也只在云函数中写了这个字段。
