### ISSUE TITLE
自动测试不可靠

### ISSUE THREAD

**Issue by hjiang** [leancloud/leanengine-node-sdk#43]
https://travis-ci.org/leancloud/leanengine-node-sdk/builds

**Comment by sdjcw** [comment]
travis-ci 访问我们国内服务器有时候会耗时特别长，导致测试超时失败。

一般是失败了我就再重新触发下，一般就能通过了。

**Comment by wangxiao** [comment]
确实。js realtime sdk 把测试用例都改为美国节点的，就都能通过 travis-ci 了。可以也改成美国节点的试试。
