### ISSUE TITLE
avos-express-https-redirect 中间件不支持 leanapp.cn

### ISSUE THREAD

**Issue by hjiang** [leancloud/leanengine-node-sdk#44]

**Comment by sdjcw** [comment]
这个不支持是指什么？我测试这个是可以的：

https://stg-leanengine-unit-test.leanapp.cn/

**Comment by hjiang** [comment]
访问 http://stg-leanengine-unit-test.leanapp.cn/ 不会 redirect 到 https

**Comment by juvenn** [comment]
我这里也正常 redirect 了。

**Comment by sdjcw** [comment]
现在可以是我在测试 fix 以后的结果。。
