### ISSUE TITLE
Usage with koa?

### ISSUE THREAD

**Issue by tiaod** [leancloud/leanengine-node-sdk#55]
[koa](https://github.com/koajs/koa) needs a generator function.So I couldn't make it works like the example:

```
// cloud.js
var AV = require('leanengine');
AV.Cloud.define('hello', function(request, response) {
  response.success('Hello world!');
});
module.exports = AV.Cloud;
```

```
var koa = require("koa");
var cloud = require('./cloud');
var app = koa();
app.use(cloud);

module.exports = app
```

It throw an error:`AssertionError: app.use() requires a generator function`.

**Comment by Tomyail** [comment]
try this [using-express-middleware-in-koa](http://stackoverflow.com/questions/25385382/using-express-middleware-in-koa)

**Comment by jysperm** [comment]
可到  https://github.com/leancloud/leanengine-node-sdk/pull/84 追踪后续进展
