### ISSUE TITLE
beforeUpdate 支持用户指定允许更新的字段

### ISSUE THREAD

**Issue by jysperm** [leancloud/leanengine-node-sdk#59]
经过和晓丹的讨论 https://github.com/leancloud/uluru-platform/issues/2101 ，beforeUpdate 中支持：

```
res.success(['a', 'b']); // 允许更新 a, b 两列
res.success(); // 兼容原有写法，等价于 res.success(req.object.updatedKeys);
```

然后 Node SDK 向云存储返回一个数组结果表示允许更新的列，旧版本会返回 req.object.

**Comment by sdjcw** [comment]
好人性化（复杂）的功能啊～～

**Comment by killme2008** [comment]
``` json
{
 "_updatedKeys": [ ]
}
```

**Comment by sdjcw** [comment]
我不太明白这个特性的需求。
客户端如果同时更新多个属性，很有可能这些属性之前存在关联性，或者说更新的原子性。而云引擎的 hook 可以轻易的打破这种约束，导致某些字段更新，而另一些字段没有更新，更尴尬的事这事发生的时候，客户端完全不知情，而且可能还缓存了错误的修改（服务端个别字段没有更新，但是客户端收到更新响应 200，认为所有更新都有效）。

**Comment by jysperm** [comment]
这个功能还是不做了，确实如陈伟所说，加了之后会引入一种「部分成功」的状态，会增加很多复杂度。而且最近很长一段时间，并没有遇到需要这个特性才能满足的需求。
