### ISSUE TITLE
Please use AV._config.APIServerURL to replace AV.serverURL 

### ISSUE THREAD

**Issue by jysperm** [leancloud/leanengine-node-sdk#62]

**Comment by hjiang** [comment]
这里能不能做个向前兼容的改动，能不能 hook 一下对 AV.serverURL 的访问，打印一个 deprecation warning，但是 forward 到 AV._config.APIServerURL，保证可用。

**Comment by jysperm** [comment]
是兼容的，只是会打印警告。这是 JavaScript 那边的修改，所以 Node SDK 要跟着改，去掉警告。
