### ISSUE TITLE
cookie-session 中向 req 添加了 sessionCookies、sessionOptions、sessionKey 属性

### ISSUE THREAD

**Issue by jysperm** [leancloud/leanengine-node-sdk#63]
https://github.com/leancloud/leanengine-node-sdk/blob/0.4.0/lib/avosExpressCookieSession/index.js#L39-L43

但似乎这三个属性并没有被用到，却会增加和其他 session 中间件冲突的风险。

**Comment by aisk** [comment]
我们还是搞个命名空间（AV?）比较方便

**Comment by jysperm** [comment]
现在我们在 request 对象上确实有个叫 AV 的对象当作命名空间来用。

**Comment by jysperm** [comment]
2.0 中删去了 sessionCookies https://github.com/leancloud/leanengine-node-sdk/pull/102
