### ISSUE TITLE
添加一个 AV.Cloud.onError 的方法来监听云函数的错误以便用户实现自己的错误处理逻辑

### ISSUE THREAD

**Issue by jysperm** [leancloud/leanengine-node-sdk#67]
AV.Cloud.run 支持 Promise 方式调用

**Comment by jysperm** [comment]
https://forum.leancloud.cn/t/js-router/10044 有用户反馈希望 AV.Cloud.run 在出错时不向标准输出打印错误信息。

**Comment by leeyeh** [comment]
如果废弃回调的接口，用户必须处理返回的 Promise，是不是就不用打这个日志了。

**Comment by jysperm** [comment]
已在 https://github.com/leancloud/leanengine-node-sdk/pull/102 实现
