### ISSUE TITLE
考虑让 JS SDK 版本用户可自定

### ISSUE THREAD

**Issue by wangxiao** [leancloud/leanengine-node-sdk#86]

**Comment by jysperm** [comment]
和 https://github.com/leancloud/leanengine-node-sdk/issues/54 重复。

目前主要是因为 JS SDK 每个版本都有比较大的修改，所以为了避免问题暂时还是锁定了 JS SDK 的版本。以后如果 JS SDK 比较稳定了可以考虑放开，最好是默认锁版本，但给用户一个比较方便的方式来替换掉默认的版本。

**Comment by jysperm** [comment]
已将版本约束放宽到 `~1.3.2`，更多有关 peerDependency 的讨论请到  https://github.com/leancloud/leanengine-node-sdk/issues/54 进行
