### ISSUE TITLE
云函数提供 Promise 支持

### ISSUE THREAD

**Issue by jysperm** [leancloud/leanengine-node-sdk#90]
之前曾在 https://github.com/leancloud/cloud-code/issues/756 讨论过，结论是因为 Promise 只能够表示「成功」和「不成功」两种状态，而我们的云函数实际上有「成功」、「失败」、「出现异常」三种情况。

目前云函数会用 domain 捕捉异步的异常，但因为 domian 本身的不确定性，在之后的 Node 版本中不好保证一定有效。@leeyeh 提议支持用 Promise 去表示「出现异常」的情况，即也去捕捉通过 Promise 传递出的异常，保持和同步异常一样的处理方式。

**Comment by sdjcw** [comment]
云引擎移除 domain 的使用吧。
失败和出现异常都可以归为 不成功，感觉没什么问题。

**Comment by jysperm** [comment]
打算这样来做，继续兼容老的云函数定义方法，但如果传递给 AV.Cloud.define 的函数定义只有一个参数，就启用 Promise 模式：

```
AV.Cloud.define(function(request) {
  return new AV.Query('Post').find().then( posts => {
    if (posts.length > 0) {
      return posts[0];
    } else {
      throw new AV.Cloud.Error('posts is empty');
    }
  });
});
```

包括 AV.Cloud.beforeSave 等 Hook 也是这样，至于 after 类的 Hook 本来就是一个参数，但也没关系，因为 after 类的 Hook 本来也不关心响应。

Promise 模式下用 Promise 的值作为云函数的响应，如果 Promise 中抛了使用 AV.Cloud.Error 构造的异常，则作为错误返回给客户端（默认 status=400，code=1），AV.Cloud.Error 提供第二个参数来设置 status 和 code `AV.Cloud.Error('posts is empty', {status: 422, code: 422})`；如果 Promise 中抛了其他异常则视作服务器端错误，返回 500 响应并打印错误到标准输出。

**Comment by jysperm** [comment]
@aisk @leeyeh

**Comment by leeyeh** [comment]
使用参数长度作为区分的做法并不优雅。之前使用 `response.success`/`response.fail` 的方式会存在多次调用、我们无法感知结果等问题，因此 Promise 应该是理想的方案。所以我觉得我们应该优先 Promise 的支持，然后尽可能兼容之前 response 的用法（并且应该标记为废弃）。而不是「兼容 Promise」。

**Comment by jysperm** [comment]
或者你可以说默认启用 Promise 模式，当参数数量是两个的时候再兼容 response.success/error。

**Comment by leeyeh** [comment]
LGTM

**Comment by jysperm** [comment]
已在 https://github.com/leancloud/leanengine-node-sdk/pull/102 实现
